### ISSUE TITLE
ndnコマンドとdnコマンドを分離したい

### ISSUE THREAD

**Issue by aknorsh** [k-seta/trpg-bot#33]
# 問題点
mayokinモードにて、 `/ndn` コマンドがtxtからの乱択と成否判定の両方に使われている。ndn以降の文を見てこれを判断するのは煩雑になりそう。

# 提案
txtからの乱択には `/dn` コマンドを使用し、成否判定等には `/ndn` を使用する、というふうに明確に分離しておくとよさそう。

**Comment by k-seta** [comment]
`/2d6 才覚ハプニング表` みたいなのはどうするつもりでしょうか？

**Comment by aknorsh** [comment]
2d6パターンがあるのか。。。 `d12` とかを新設して内部的に2d6を実行させるのも渋い感じがありますねぇ。

であれば、ndnによるtxtからの乱択を許した上で、interp_command時にコマンドの種類を識別するのがよいかもしれません。

**Comment by aknorsh** [comment]
表からの乱択時のsyntaxを変更しちゃうのも手かと思いました。たとえば、
`/2d6 = 才覚ハプニング表`
というように、=を含めてもらうなど

**Comment by k-seta** [comment]
`=` による syntax は `MayokinMode` に実装する想定？

**Comment by aknorsh** [comment]
CommandInterpreterで、
```
      if '=' in match_dice.group(0):
        return 'choice', match_dice.groups()
      else:
        return 'calc', match_dice.groups()
```
というふうに処理を分けるつもりでした。

diceメソッド内でダイス値判定とtxt乱択を両方処理すると実装が複雑になっちゃうので、メソッドを分けたいと考えております

**Comment by aknorsh** [comment]
それなら、/choice 2d6 王国表　みたいなsyntaxにしちゃえばよい、という説はある(入力が煩雑なのはアレですが

**Comment by k-seta** [comment]
取り敢えず、 `/choice 2d6 王国表` は無しかな

**Comment by k-seta** [comment]
`=` は普通に数値判定で `/2d6 = 達成値` とかみたいに使うかもしれないから、`CommandInterpreter.interp_command` の段階で切り分けをしちゃうのは微妙な気もする

**Comment by k-seta** [comment]
正直俺は今のコードでも十分読みやすい気がするんだけど、#17 を実装しようとすると微妙な気がするって話なのかな？

**Comment by aknorsh** [comment]
必須とまでは言わないが、ちょっと微妙かもと思っています。

・現状DefaultModeのdice内でsum_dicesを返しているが、左辺値に能力値が混ざってくるとこの計算は各Modeでしか行えないものになる。したがって、diceメソッドの返り値の構成を見直す必要がある。
・また、stringを返しこれにstringを追加していくのも、1)能力値名は各modeで必要だから能力値名を渡す必要がある点、2)能力値計算が終わるまでstringが確定しない点、が懸念。
・diceメソッドの返り値を [ '2d6', '+', '才覚', '<', '20' ]とし、各modeにこのリストを渡してMode内で処理するのがよさそう( #32 )。そうすると、最終的にはstringを返すべきだから、各modeのdiceメソッドでこの処理を行うとリストとstringで返り値が合わなくなる。（最終的にリストを返すのはtxt乱択のときが大変なので渋い）
・別のメソッドをつくって、そこからsuper.dice()を呼ぶ方針。別メソッドにするならcalcとchoiceでそれぞれメソッドをつくってもいいのでは（これは諸説あるかも）
・であれば、interp_commandの時点で呼ぶメソッドが判明しているべき
という考えです。

=やchoiceがない文法でも、if match_d66 or match_ndn_txtとかすれば大丈夫そうだなって思い直してきました。

（長文すまぬ。自分の頭の整理を兼ねておりました）

**Comment by k-seta** [comment]
> diceメソッドの返り値の構成を見直す必要がある

分かる
> stringを返しこれにstringを追加していくのも、1)能力値名は各modeで必要だから能力値名を渡す必要がある点、2)能力値計算が終わるまでstringが確定しない点、が懸念

1) -> これは、子クラス特有処理を解決してから、最後に `super.dice()` を呼ぶ構成にすれば、ある程度解決できそう。
2) -> これについてはどう足掻いても確定しないのでは？
> diceメソッドの返り値を [ '2d6', '+', '才覚', '<', '20' ]とし、各modeにこのリストを渡してMode内で処理するのがよさそう( #32 )

よく分からず。 #32　は、 `CommandInterpreterLogic.interp_command(command)` で、 `dn` or `ndn` が返るときの返り値タプルが `( '2d6', '+', '才覚', '<', '20' )` になると思ってたけど、違うの？

> 別のメソッドをつくって、そこからsuper.dice()を呼ぶ方針。別メソッドにするならcalcとchoiceでそれぞれメソッドをつくってもいいのでは

これもよく分からず。今はファクトリメソッドもどきの構成を採用しているので、 `trpg_bot.py` からは `mode` が共通で所有しているメソッドしか呼べない。もし、子クラスだけが持っているメソッドを呼べるようにするなら、 `trpg_bot.py` と `CommandInterpreterLogic` の実装を見直さなきゃいけなくなるからびみょい。

元々 aknorsh が言っているように、親クラスに別々のメソッドを作るのほうが、まだ実装方針と整合性が取れると思う。

> =やchoiceがない文法でも、if match_d66 or match_ndn_txtとかすれば大丈夫そうだなって思い直してきました

これは今の実装がそれに近いかな。

**Comment by k-seta** [comment]
```
CommandInterpreterLogic.interp_command(command) {
  return 'dice', tuple
}

MayokinMode.dice(tuple) {
  result = []
  for x in tuple:
    if x == match_param:
      処理
      result.append
    elif x == match_表:
      処理
      result.append
    return super().dice(result)
}

DefaultMode(tuple) {
  result = []
  for x in result:
    if x == match_ndn:
      result.append(DiceLogic.roll_ndn())
    elif x == match_ndn:
      result.append(DiceLogic.roll_n66())
    elif type(x) == tuple and type(x[0]) == function and type(x[1] == int):
      result.append(x[0](result[x[1]]))
    return (resultの整形結果)
}
```

みたいにして、

```
CommandInterpreterLogic.interp_command
=> 'dice', ( '2d6', '+', '才覚', '>', '20' )

MayokinMode.dice(( '2d6', '+', '才覚', '>', '20' ))
=> super().dice(( '2d6', '+', 5, '>', '20' ))

DefaultMode.dice(( '2d6', '+', 5, '>', '20' ))
=> ('7 [2, 5] + 5  > 20')
```

とか

```
CommandInterpreterLogic.interp_command
=> 'dice', ( 'd66', '二つ名表a' )

MayokinMode.dice(( 'd66', '二つ名表a' ))
=> super().dice('d66', ((lambda key:diceListLogic.getList('二つ名表a.txt')[key]), 0))

DefaultMode.dice('d66', (lambda key:diceListLogic.getList('二つ名表a.txt')[key]), 0))
=> ('23: xxxxxxxxxxxxx')
```

みたいな感じはどうすか？
※書いてて、本当にこんなの実装できるか？となってきた

**Comment by aknorsh** [comment]
> 1 -> これは、子クラス特有処理を解決してから、最後に super.dice() を呼ぶ構成にすれば、ある程度解決できそう。
> 2 -> これについてはどう足掻いても確定しないのでは？

1: や、これはたしかに。
2: については、そのとおりです。なので、内部的にstringをやりとりせずリストの状態で渡し、各コマンドに対応するメソッド（choiceとかcalcとか言ってるやつ）の最後でstring化してtrpg_botに返したい。

> よく分からず。 #32　は、 CommandInterpreterLogic.interp_command(command) で、 dn or ndn が返るときの返り値タプルが ( '2d6', '+', '才覚', '<', '20' ) になると思ってたけど、違うの？

#32 を書いたときはdefaultModeでの処理を想定していたが、interp_commandの時点でリストにしちゃう方がたしかにベターですな。 #35 のこともあるし。

> これもよく分からず。今はファクトリメソッドもどきの構成を採用しているので、 trpg_bot.py からは mode が共通で所有しているメソッドしか呼べない。もし、子クラスだけが持っているメソッドを呼べるようにするなら、 trpg_bot.py と CommandInterpreterLogic の実装を見直さなきゃいけなくなるからびみょい。

defaultModeで
```python
    def calc(self, message):
        raise Exception('Invalid mode')

    def choice(self, message):
        raise Exception('Invalid mode')
```
ってしておいて、子クラスでそれぞれ実装、みたいにする想定でした。が、ファクトリメソッドの設計上の利点を毀損している感じがあるので、あんまよくないかもしれぬ。

===

https://github.com/k-seta/trpg-bot/issues/33#issuecomment-632167037
で提案されている実装案について、これで十分に機能しそうだし、diceメソッドの返り値をstringで統一できるし、defaultModeでもサイコロ振れるし、僕が第一級関数が好きだしで、よさそうだと思います。
ただ、計算結果に能力値のkeyを含めたいなと思ったのですが、どうでしょうか。
自分の打ったコマンドと見比べるのもなぁという気がしている。

**Comment by k-seta** [comment]
@aknorsh 
#42 #43  で分離しないで実装したが、当初懸念していた問題は潰せたの思うので、問題なければクローズしちゃってください。

**Comment by aknorsh** [comment]
クローズでよきです。
