### ISSUE TITLE
discord.pyのmessageクラスに依存している箇所を最小限にする

### ISSUE THREAD

**Issue by aknorsh** [k-seta/trpg-bot#35]
# 問題
引数にdiscord.pyのmessageクラスを渡している箇所が複数ある。messageクラスに依存しちゃってて微妙。

# タスク
たとえば、
```python
def dice(self, message):
  terms = message.content.split('+')
```
などは、事前にcontentを取り出して文字列で渡す（messageクラスに依存させない）などする。

**Comment by k-seta** [comment]
#42 で消せたけど、まだ残っている部分があるのでクローズしません
